### ISSUE TITLE
release 1.2 may need a different guava?

### ISSUE THREAD

**Issue by jinm** [logstash-plugins/logstash-input-google_pubsub#34]
Docker 1.11.1
Image: docker.elastic.co/logstash/logstash:6.2.4
Logstash input:

`
  google_pubsub {
      project_id => "myproject"
      topic => "logstash-input-dev"
      subscription => "logstash-sub"
      json_key_file => "/tmp/key.json"
  }
`

Error:
"java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;J)V"

Release 1.10 seems OK. Is there anything end user should do?

Thanks.

Jin.

**Comment by SebScoFr** [comment]
Same here on my production pipeline
`[2018-05-10T10:19:59,800][ERROR][org.logstash.Logstash    ] java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;J)V`

**Comment by josephlewis42** [comment]
@tacomafour would you be willing to do a PR on your patch?

**Comment by tacomafour** [comment]
Yes, that was my intent from the start. It got late and I ran out of time to issue a nice and tidy PR. 
I was trying to figure out why the master was failing in Travis because I knew my PR would fail as a result. Then it was after midnight :-) 
I'll submit it in a few hours after I'm done at work today. 
 
 
  On Thu, May 10, 2018 at 11:50, Joseph Lewis III<notifications@github.com> wrote:   
@tacomafour would you be willing to do a PR on your patch?

**Comment by josephlewis42** [comment]
@tacomafour Thanks!

I think master was failing due to a known bug upstream, I re-ran it and it's fixed now.

**Comment by josephlewis42** [comment]
Hey all, this was fixed upstream, but unfortunately it won't make it in time for 6.3.0, so it'll be fixed in 6.3.1.

More here: https://github.com/elastic/logstash/pull/9622

In the meantime the solution is to roll back to v1.1 of the plugin or keep your Logstash at 6.2.3.
